case $- in
*i*) ;;
*) return ;;
esac

HISTCONTROL=ignoreboth

shopt -s histappend

HISTSIZE=1000
HISTFILESIZE=2000

shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

case "$TERM" in
xterm-color | *-256color) color_prompt=yes ;;
esac

if [ -n "$force_color_prompt" ]; then
  if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
    color_prompt=yes
  else
    color_prompt=
  fi
fi

if [ "$color_prompt" = yes ]; then
  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
  PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

case "$TERM" in
xterm* | rxvt*)
  PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
  ;;
*) ;;
esac

if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
fi

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export PATH=$PATH:/home/datadiego/.local/bin
export PATH="$PATH:/opt/nvim-linux-x86_64/bin"

eval "$(oh-my-posh init bash --config ~/.config/oh-my-posh/eva01.json)"
export LS_COLORS="di=38;2;135;95;175:fi=38;2;230;187;133:ln=38;2;135;255;95:ex=38;2;142;223;95:*.tar=38;2;206;103;240:*.gz=38;2;206;103;240:*.zip=38;2;206;103;240:bd=38;2;217;145;69:cd=38;2;217;145;69:or=38;2;191;45;45:*.py=38;2;230;187;133"
eval "$(zoxide init bash)"

alias n='nvim'
alias ls='exa -l --color=always --icons'
alias ll='exa -l --icons'
alias cd='z'
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# opencode
export PATH=/home/datadiego/.opencode/bin:$PATH
