#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar
polybar example &

feh --bg-fill ~/.config/wallpapers/wallpaper.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off

pgrep -x picom > /dev/null || picom &

# picom --experimental-backends --config ~/.config/picom/picom.conf &

# xsettingsd para aplicar temas GTK en BSPWM
pgrep -x xsettingsd > /dev/null || xsettingsd &

