set nocompatible
filetype plugin on
syntax on

" Lightline
set laststatus=2

" Opcional: tema de lightline
let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }

" interfaz
set number
set relativenumber
set cursorline
"set showcmd
"set wildmenu

" indentación
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

" búsqueda
set ignorecase
set smartcase
set incsearch
set hlsearch

" splits
set splitbelow
set splitright

" colores
syntax on
set termguicolors
colorscheme torte

" clipboard del sistema
set clipboard=unnamedplus

" scrolling cómodo
set scrolloff=8

" explorador de archivos
nnoremap <leader>e :Ex<CR>
